"""Energy column for User.Stats

Revision ID: 058ff21e6c4c
Revises: f99a582cfdc2
Create Date: 2026-03-30 19:37:21.153948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058ff21e6c4c'
down_revision: Union[str, Sequence[str], None] = 'f99a582cfdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('energy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'energy')
    # ### end Alembic commands ###
