"""Update gardens table finish time

Revision ID: 3d250580941b
Revises: 982ec50a2e54
Create Date: 2026-04-05 12:59:33.676443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d250580941b'
down_revision: Union[str, Sequence[str], None] = '982ec50a2e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('finish_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'finish_time')
    # ### end Alembic commands ###
