"""Added column referer id to user table

Revision ID: 468035fb1caf
Revises: b27441b4ce72
Create Date: 2026-04-01 18:46:48.374393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468035fb1caf'
down_revision: Union[str, Sequence[str], None] = 'b27441b4ce72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referer_id')
    # ### end Alembic commands ###
