"""Update gardens table phase counter

Revision ID: 6e8b2f59692f
Revises: 3d250580941b
Create Date: 2026-04-05 13:03:25.638467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8b2f59692f'
down_revision: Union[str, Sequence[str], None] = '3d250580941b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('phase_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'phase_counter')
    # ### end Alembic commands ###
