"""Energy columns for Player

Revision ID: 8846c21b8977
Revises: a0f74199a2df
Create Date: 2026-03-30 19:54:35.949186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8846c21b8977'
down_revision: Union[str, Sequence[str], None] = 'a0f74199a2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('max_energy', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('energy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'energy')
    op.drop_column('players', 'max_energy')
    # ### end Alembic commands ###
