"""Update gardens table

Revision ID: 982ec50a2e54
Revises: 468035fb1caf
Create Date: 2026-04-05 12:26:57.716869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982ec50a2e54'
down_revision: Union[str, Sequence[str], None] = '468035fb1caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('current_phase', sa.Integer(), nullable=True))
    op.add_column('gardens', sa.Column('next_event_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'next_event_time')
    op.drop_column('gardens', 'current_phase')
    # ### end Alembic commands ###
