"""Max energy column

Revision ID: a0f74199a2df
Revises: 058ff21e6c4c
Create Date: 2026-03-30 19:47:58.059823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f74199a2df'
down_revision: Union[str, Sequence[str], None] = '058ff21e6c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('max_energy', sa.Integer(), nullable=False))
    op.alter_column('players', 'energy',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'energy',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('players', 'max_energy')
    # ### end Alembic commands ###
