"""Removed boost column on gardens, added hydration

Revision ID: a9e2770abf22
Revises: bf1967438ceb
Create Date: 2026-03-31 14:18:44.124939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e2770abf22'
down_revision: Union[str, Sequence[str], None] = 'bf1967438ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('hydration', sa.Float(), nullable=True))
    op.drop_column('gardens', 'boost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('boost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gardens', 'hydration')
    # ### end Alembic commands ###
