"""Removed boost column on gardens, added hydration

Revision ID: b27441b4ce72
Revises: a9e2770abf22
Create Date: 2026-03-31 14:21:02.825592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27441b4ce72'
down_revision: Union[str, Sequence[str], None] = 'a9e2770abf22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
