"""Added column boost to garden table

Revision ID: bf1967438ceb
Revises: 8846c21b8977
Create Date: 2026-03-31 11:08:12.480687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1967438ceb'
down_revision: Union[str, Sequence[str], None] = '8846c21b8977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('boost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'boost')
    # ### end Alembic commands ###
